### ISSUE TITLE
Return and Refund Policy Page Design

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#18]
@Thimmy017 and @Subomiveronica, please design this page so that @Myxic can develop it. Comment the link to your designs here.

**Comment by Thimmy017** [comment]
https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=9%3A2

**Comment by Subomiveronica** [comment]
https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=9%3A2

**Comment by Subomiveronica** [comment]
https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=9%3A2

**Comment by Myxic** [comment]
https://github.com/zuri-training/Tcgen-team80/tree/main/termsgen/templates/termsgen/return%20and%20refund%20pages

**Comment by Myxic** [comment]
https://github.com/zuri-training/Tcgen-team80/tree/main/termsgen/static/termsgen/return%20and%20refund
THE CSS AND JAVASCRIPT
