### ISSUE TITLE
Contact us and About us pages

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#20]

**Comment by orefakolujo** [comment]
@Bennyspicey , please design this page so that @Increaze can build the frontend. Comment the link to your designs here.

**Comment by Bennyspicey** [comment]
okay already working on it

**Comment by Bennyspicey** [comment]
@Increaze i am done with the design for the contact us page and about us page, all the final edits has been done also now you can check it out

**Comment by Bennyspicey** [comment]
@Increaze  @orefakolujo https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=45%3A8 this is the link to the completed contact us and about us design

**Comment by Increaze** [comment]
@orefakolujo 
I've created a pull request for the contact page...Please merge and review

**Comment by Increaze** [comment]
Completed
