### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#22]
@Eliteconcept , please design this page so that @Osaode can build the frontend. Comment the link to your designs here.

**Comment by Osaode** [comment]
Frontend development is done ✅

**Comment by Eliteconcept** [comment]
Thank you Ore, the UI development is done, you can view the complete designs from this link

https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=0%3A1

**Comment by Osaode** [comment]
Work completed and dashboard front end running smoothly
