### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#24]
@Melissa-Dayveeds and @Hajarahbjay , please design this page so that @AnitaAO  can build the frontend. Comment the link to your designs here.

**Comment by Hajarahbjay** [comment]
This task has been completed.. Thanks

**Comment by Hajarahbjay** [comment]
https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=8%3A2

**Comment by Melissa-Dayveeds** [comment]
We have successfully completed the design… @Hajarahbjay has dropped the link to the page
