### ISSUE TITLE
Terns and Conditions

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#26]
@casenora , please design this page so that @Augustine-Geeft  can build the frontend. Comment the link to your designs here.

**Comment by casenora** [comment]
https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO/Wireframe-TermsGen?node-id=43%3A2

**Comment by Augustine-Geeft** [comment]
The frontend design for the terms and conditions pages is all set up and has been pushed to the Github repo.

**Comment by casenora** [comment]
Awesome,way to go thanks!
