### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by orefakolujo** [zuri-training/Tcgen-team80#27]
@Britney-O and @Bennyspicey, Please work on the style guide.

**Comment by Bennyspicey** [comment]
@orefakolujo on it now with @Britney-O

**Comment by Bennyspicey** [comment]
@Britney-O  and i are done with the style guide @orefakolujo

**Comment by Britney-O** [comment]
Done 

https://www.figma.com/file/Rlo2EeDc8rWUn9wMV7aboO?node-id=123:105
