### ISSUE TITLE
Research documentation

### ISSUE THREAD

**Issue by Osaode** [zuri-training/Tcgen-team80#42]
@Eliteconcept and @Britney-O please compile the research documentation for our project

**Comment by Britney-O** [comment]
Done!

https://docs.google.com/document/d/12jgXlrcLgm9036wlhCjBQm_Kf-kMVzCoUXxW1ZHB7AE/edit?usp=sharing

**Comment by Eliteconcept** [comment]
@OsaodeWe have completed this documentation and the link has been attached by @Britney-O
