### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by Osaode** [zuri-training/Tcgen-team80#44]
@Melissa-Dayveeds and @mayorks please create the user flow for our project

**Comment by Melissa-Dayveeds** [comment]
@mayorks and I have created the user flow… you can find the link to the fig jam board below 

https://www.figma.com/file/HTUP8bXVP5m3BPK1HAeSdI/Zuri-team-80-user-flow?node-id=0%3A1

**Comment by mayorks** [comment]
@Melissa-Dayveeds and I worked together on the user flow. Here's the link below:

https://www.figma.com/file/HTUP8bXVP5m3BPK1HAeSdI/Zuri-team-80-user-flow?node-id=0%3A1
