### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Osaode** [zuri-training/Tcgen-team80#46]
@CommyC4 and @Britney-O please create the prototypes for our page designs of our project

**Comment by Britney-O** [comment]
Done

https://www.figma.com/file/6cp5gzdydWZF64P1zTxprg/T_C-Gen-Proj-Team80(Termsgen)-(Copy)?node-id=24%3A23602

**Comment by CommyC4** [comment]
Done

https://www.figma.com/file/6cp5gzdydWZF64P1zTxprg/T_C-Gen-Proj-Team80(Termsgen)-(Copy)?node-id=24%3A23602
